"""change_release_info_column_name

Revision ID: 77263c67479f
Revises: 259e2a9fc15e
Create Date: 2022-03-19 20:19:13.821574

"""
import sqlalchemy as sa
import sqlalchemy.orm as orm
from alembic import op

# revision identifiers, used by Alembic.
revision = '77263c67479f'
down_revision = '259e2a9fc15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = orm.Session(bind=op.get_bind())
    session.execute(
        "ALTER TABLE product_release_info " +
        "RENAME delay_release_date TO adjusted_release_date;"
    )
    session.commit()
    session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = orm.Session(bind=op.get_bind())
    session.execute(
        "ALTER TABLE product_release_info " +
        "RENAME adjusted_release_date TO delay_release_date;"
    )
    session.commit()
    session.close()
    # ### end Alembic commands ###
