"""change source_checksum and periodic_task schema

Revision ID: a37b35b25ceb
Revises: 4d6b97fac8ed
Create Date: 2022-06-06 12:27:17.675738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from app.models import Task, SourceChecksum


# revision identifiers, used by Alembic.
revision = 'a37b35b25ceb'
down_revision = '4d6b97fac8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    op.add_column('periodic_task', sa.Column(
        'id', sa.Integer(), autoincrement=True, nullable=True))
    op.drop_constraint('periodic_task_pkey', 'periodic_task', 'primary')

    tasks = session.execute(f"SELECT * FROM periodic_task;")
    for index, row in enumerate(tasks):
        session.execute(
            f"UPDATE periodic_task SET id={index+1} WHERE name='{row.name}';")

    op.alter_column('periodic_task', 'id', nullable=False)

    op.create_primary_key('periodic_task_pkey', 'periodic_task', ['id'])
    op.alter_column('periodic_task', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)

    op.add_column('source_checksum', sa.Column(
        'id', sa.Integer(), autoincrement=True, nullable=True))
    op.drop_constraint('source_checksum_pkey', 'source_checksum', 'primary')

    checksums = session.execute(f"SELECT * FROM source_checksum;")
    for index, row in enumerate(checksums):
        session.execute(
            f"UPDATE source_checksum SET id={index+1} WHERE name='{row.source}';")

    op.alter_column('source_checksum', 'id', nullable=False)
    op.create_primary_key('source_checksum_pkey', 'source_checksum', ['id'])
    op.alter_column('source_checksum', 'source',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_checksum', 'source',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('source_checksum', 'id')
    op.create_primary_key('source_checksum_pkey',
                          'source_checksum', ['source'])

    op.alter_column('periodic_task', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('periodic_task', 'id')
    op.create_primary_key('periodic_task_pkey', 'periodic_task', ['name'])
    # ### end Alembic commands ###
